name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
      - name: Install system OpenGL/EGL libs (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1 libgl1
          echo "QT_QPA_PLATFORM=offscreen" >> $GITHUB_ENV
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: CLI version smoke test
        run: python -m psm.cli --version
      - name: Run tests
        run: pytest -q
      - name: Documentation - Link Check
        if: matrix.os == 'ubuntu-latest' && matrix.python == '3.12'
        run: python scripts/check_links.py
      - name: Code Quality - Analysis
        if: matrix.os == 'ubuntu-latest' && matrix.python == '3.12'
        run: python scripts/analyze_code.py all
        continue-on-error: true
      - name: Summary
        if: always() && matrix.os == 'ubuntu-latest' && matrix.python == '3.12'
        run: |
          echo "### CI Summary - ${{ matrix.os }} Python ${{ matrix.python }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Tests completed" >> $GITHUB_STEP_SUMMARY
          echo "✅ Documentation links checked" >> $GITHUB_STEP_SUMMARY
          echo "✅ Code quality checks completed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Review the job logs for details on any warnings or issues." >> $GITHUB_STEP_SUMMARY
