name: Code Format Check

on:
  push:
    branches: [ main, develop ]
    paths:
      - '**.py'
      - 'pyproject.toml'
      - '.github/workflows/format-check.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - '**.py'
      - 'pyproject.toml'

jobs:
  format-check:
    name: Check Python Code Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black>=24.0.0

      - name: Check code formatting with Black
        run: |
          python -m black --check --diff --color psm tests scripts

      - name: Format check summary
        if: failure()
        run: |
          echo "❌ Code formatting check failed!"
          echo ""
          echo "Some files are not formatted according to Black style."
          echo "To fix formatting issues, run locally:"
          echo "  run.bat py -m black psm tests scripts"
          echo "Or use the cleanup script:"
          echo "  run.bat py scripts/cleanup_code.py all"
